name: tripledes_nullsafety
description: Triple DES and DES block cipher implementation ported from CryptoJS
version: 1.0.2
homepage: https://github.com/nelstein/tripledes-dart

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies: 
  flutter:
    sdk: flutter

dev_dependencies:
  test:

